
name: built_vector
version: 0.1.0
description: Generate Flutter vector code from SVG-like files.
authors:
- Aloïs Deniel <alois.deniel@outlook.com>
homepage: https://github.com/aloisdeniel/built_vector
dependencies:
  xml: ^3.2.3
  source_gen: ^0.9.1
  code_builder: ^3.1.3
  path_parsing: ^0.1.3
  args: ^1.5.1
  recase: ^2.0.0